### PR TITLE
Program to check for Special Number.

### PR DESCRIPTION
**Pull request by rakshitgupta23**
I have added a program which shows the implementation of special number in C.

### CODE REVIEW

**Comment by rakshitgupta23** [comment]
@Ayushd70 Please review my PR.

**Comment by Ayushd70** [comment]
can you rename the file to **c/specialNumber.c** and also update the commit message to **c:  check special number**.

**Comment by rakshitgupta23** [comment]
> can you rename the file to **c/specialNumber.c** and also update the commit message to **c: check special number**. Also add a EOL to the file

Ok I will certainly do all the changes. But can you tell me what is meant by EOL?

**Comment by Ayushd70** [comment]
> > can you rename the file to **c/specialNumber.c** and also update the commit message to **c: check special number**. Also add a EOL to the file
> 
> I have made both the changes. But can you tell me what is meant by EOL?

Add a blank line to the end of the file.

**Comment by rakshitgupta23** [comment]
> > > can you rename the file to **c/specialNumber.c** and also update the commit message to **c: check special number**. Also add a EOL to the file
> > 
> > 
> > I have made both the changes. But can you tell me what is meant by EOL?
> 
> Add a blank line to the end of the file.

@Ayushd70  I have added a blank line. Please review it now.

**Comment by Ayushd70** [comment]
> > > > can you rename the file to **c/specialNumber.c** and also update the commit message to **c: check special number**. Also add a EOL to the file
> > > 
> > > 
> > > I have made both the changes. But can you tell me what is meant by EOL?
> > 
> > 
> > Add a blank line to the end of the file.
> 
> @Ayushd70 I have added a blank line. Please review it now.

awesome, merged.

**Pull request merged**
